import esbuild from 'esbuild'
import esbuildSvelte from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'
import { builtinModules } from 'node:module'
import process from 'process'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Lean Search - source: https://github.com/felixleopold/lean-search
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  outfile: 'dist/main.js',
  format: 'cjs',
  target: 'chrome108',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  plugins: [
    esbuildSvelte({
      compilerOptions: { css: 'injected', dev: !prod },
      preprocess: sveltePreprocess(),
    }),
  ],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
